[package]
name = "datafusion-materialized-views-common"
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
keywords.workspace = true
rust-version.workspace = true

[dependencies]
datafusion-common.workspace = true